apiVersion: v1
kind: DeploymentConfig
metadata:
  labels:
    app: fiercesw-workshops
  name: fiercesw-workshops
spec:
  replicas: 1
  selector:
    app: fiercesw-workshops
    deploymentconfig: fiercesw-workshops
  strategy:
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      labels:
        app: fiercesw-workshops
        deploymentconfig: fiercesw-workshops
    spec:
      containers:
      - image: prod-site-workshops-fiercesw-network/fiercesw-workshops:latest
        imagePullPolicy: Always
        name: fiercesw-workshops
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - fiercesw-workshops
      from:
        kind: ImageStreamTag
        name: fiercesw-workshops:latest
    type: ImageChange
