title = "Red Hat | Fierce Software Workshops"
baseURL = "http://workshops.fiercesw.network:8080/redhat/"
theme = "fiercesw-dark"
languageCode = "en-us"
metaDataFormat = "yaml"

[params]
    description = "Tried. Tested. Trusted."

[taxonomies]
    workshop = "workshops"

[blackfriday]
    smartypants = false

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Workshops"
    identifier = "workshops"
    weight = 100
